Tau1_pt:
  x_bins: [ 20, 40, 60, 80, 100, 125, 150, 175, 200, 250, 300 ]
  x_title: "leading #tau_{h} p_{T} (GeV)"
  y_title: "dN/dm (1/GeV)"
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: True
