- name: DY
  title: "DY #rightarrow ll + jets"
  color: kYellow
- name: TT
  title: t#bar{t}
  color: kRed-3
- name: W
  title: "W #rightarrow l#nu + jets"
  color: kViolet-6
- name: HNL
  title: "HNL #rightarrow 3l m_{HNL} = 300 GeV (x 1e6)"
  type: signal
  color: kBlack
  scale: 1000000.
- name: data
  title: "Data"
  type: data
