MT2:
  x_bins: [ 0, 25, 50, 75, 100, 125, 150, 175, 200, 250, 300, 500 ]
  x_title: MT2_{H} (GeV)
  #y_title: dN/dm (1/GeV)
  y_title: Events
  use_log_y: False
  max_y_sf: 1.5
  divide_by_bin_width: False
